on:
  pull_request:
    branches:
      - master

jobs:
  run:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn
      
      - run: yarn generate
      
      - name: Read replies.md
        id: replies
        uses: juliangruber/read-file-action@v1
        with:
          path: ./dist/replies.md

      - name: Leave replies
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Comments
            ${{ steps.replies.outputs.content }}
          reaction-type: 'rocket'
